.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -157,10 +157,12 @@ stages:
         export AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
         export AWS_SECRET_ACCESS_KEY=${S3_ACCESS_SECRET}
         export AWS_DEFAULT_REGION=${S3_REGION}   
-        aws s3 ls s3://${S3_BUCKET_NAME}/${S3_FOLDER}/${ID_DEMANDE}.zip \
-          --region ${S3_REGION} \
-          && echo "File ${ID_DEMANDE}.zip fetched" \
-          || { echo "Could not fetch ${ID_DEMANDE}.zip file"; exit 1 }
+        if aws s3 ls s3://${S3_BUCKET_NAME}/${S3_FOLDER}/${ID_DEMANDE}.zip --region ${S3_REGION}; then
+          echo "File ${ID_DEMANDE}.zip fetched"
+        else
+          echo "Could not fetch ${ID_DEMANDE}.zip file"
+          exit 1
+        fi
       displayName: 'Check zip file in s3'
       env:
         S3_ACCESS_KEY: $(S3_ACCESS_KEY)
